"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = __importDefault(require("express"));
const router = express_1.default.Router();
exports.default = router;
const index_1 = require("../Controller/index");
const survey_1 = require("../Controller/survey");
const question_1 = require("../Controller/question");
router.get('/', index_1.DisplayHomePage);
router.get('/home', index_1.DisplayHomePage);
router.get('/survey-list', survey_1.DisplaySurveyListPage);
router.get('/add-survey', survey_1.DisplayAddSurveyPage);
router.post('/add-survey', survey_1.ProcessAddSurveyPage);
router.get('/delete-survey/:id', survey_1.ProcessDeleteSurveyPage);
router.get('/question/:id', question_1.DisplayQuestionPage);
router.post('/question/:id', question_1.ProcessQuestionPage);
router.get('/add-question-mc/:id', question_1.DisplayAddMCQuestionPage);
router.post('/add-question-mc/:id', question_1.ProcessAddMCQuestionPage);
router.get('/add-question-tf/:id', question_1.DisplayAddTFQuestionPage);
router.post('/add-question-tf/:id', question_1.ProcessAddTFQuestionPage);
router.get('/add-question-sa/:id', question_1.DisplayAddSAQuestionPage);
router.post('/add-question-sa/:id', question_1.ProcessAddSAQuestionPage);
router.get('/update-question/:id', question_1.DisplayUpdateQuestionPage);
router.post('/update-question/:id', question_1.ProcessUpdateQuestionPage);
router.get('/delete-question/:id', question_1.ProcessDeleteQuestionPage);
router.get('/date', question_1.DisplayExpiryDatePage);
router.get('/take-survey/:id', question_1.DisplayTakeSurveyPage);
router.post('/take-survey/:id', question_1.ProcessTakeSurveyPage);
module.exports = router;
//# sourceMappingURL=index.js.map